### ISSUE TITLE
Please add following paper related to Domain Adaptation accepted in IJCNN 2019 

### ISSUE THREAD

**Issue by vinodkkurmi** [barebell/DA#2]
hi @barebell  
Please add the following paper related to Domain Adaptation accepted at IJCNN 2019 
Paper: https://arxiv.org/abs/1904.01341
Project page: https://vinodkkurmi.github.io/DiscriminatorDomainAdaptation/

Thanks

**Comment by barebell** [comment]
Thank for sharing your paper! The link from arxiv.org has been add to the list.
