### ISSUE TITLE
Method suggestion for my problem

### ISSUE THREAD

**Issue by off99555** [barebell/DA#4]
Generally, my problem is about predicting facial expression from a facial image (think of the classification of emotion like happy/sad/angry/etc).
The source domain is very accurately labeled. The image comes from a frontal camera.
The target domain I do not have any labels. The image has different lighting from the environment and a slightly different camera angle.
Do you have a suggestion of a method to help me classify the target domain as accurately as possible? I do not care about accuracy for the source domain though.

What application have you used unsupervised domain adaptation for in the past?

**Comment by barebell** [comment]
ExprADA: Adversarial domain adaptation for facial expression analysis
url: https://www.sciencedirect.com/science/article/abs/pii/S0031320319304121
